import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { AgentProvider } from "@agents-workspaces/core";

export type KnowledgeScope = "global" | "project" | "repository" | "task";

export interface KnowledgeSourceInput {
  path: string;
  scope: KnowledgeScope;
  title?: string;
}

export interface KnowledgeSource extends KnowledgeSourceInput {
  contentHash: string;
  content: string;
}

export interface CompiledContext {
  provider: AgentProvider;
  targetFile: "AGENTS.md" | "CLAUDE.md";
  sources: Array<Omit<KnowledgeSource, "content">>;
  content: string;
}

const scopeRank: Record<KnowledgeScope, number> = { global: 0, project: 1, repository: 2, task: 3 };

export function targetContextFile(provider: AgentProvider): CompiledContext["targetFile"] {
  return provider === "codex" ? "AGENTS.md" : "CLAUDE.md";
}

export async function compileContext(provider: AgentProvider, inputs: KnowledgeSourceInput[]): Promise<CompiledContext> {
  const sources = await Promise.all(inputs.map(async (input): Promise<KnowledgeSource> => {
    const content = await readFile(input.path, "utf8");
    return { ...input, content, contentHash: createHash("sha256").update(content).digest("hex") };
  }));
  sources.sort((a, b) => scopeRank[a.scope] - scopeRank[b.scope] || a.path.localeCompare(b.path));
  const body = sources.map((source) => `## ${source.scope}: ${source.title ?? source.path}\n\n${source.content.trim()}`).join("\n\n---\n\n");
  return {
    provider,
    targetFile: targetContextFile(provider),
    sources: sources.map(({ content: _content, ...source }) => source),
    content: `<!-- Generated by Agents-Workspaces. Edit the source files in Obsidian. -->\n\n# Runtime Instructions\n\n${body}\n`,
  };
}

export async function writeCompiledContexts(workspacePath: string, inputs: KnowledgeSourceInput[]): Promise<CompiledContext[]> {
  const generatedDirectory = join(workspacePath, ".agents-workspaces", "generated");
  await mkdir(generatedDirectory, { recursive: true });
  const contexts = await Promise.all((["codex", "claude"] as const).map((provider) => compileContext(provider, inputs)));
  for (const context of contexts) {
    await writeFile(join(workspacePath, context.targetFile), context.content, "utf8");
    await writeFile(join(generatedDirectory, `${context.provider}-context.json`), JSON.stringify(context, null, 2), "utf8");
  }
  return contexts;
}

